#JOB 1 : iac scanning and initial security 

name: DevSecOps pipeline

on:
  push:
    branches : ["main"]
  pull_request: 
    branches : ["main"]

permissions:
  contents: read


env: 
  AWS_REGION : us-east-1
  ECR_REPOSITORY : aegis-ai-agent


jobs: 
  iac-and-static-scan:
    name: Infrastructure (IaC) & code security 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0 #pour installer all the commits


      - name: check for git leaks
        uses: gitleaks/gitleaks-action@v2
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Scan de IaC (terraform configutations)
        uses: aquasecurity/trivy-action@master
        with: 
          scan-type: 'config'
          hide-progress: true 
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: SAST (sonarcloud scan)
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=noolatifa_ai-defense-devsecops
            -Dsonar.organization=noolatifa



  # JOB 2 : secure build, container scan & aws push

  build-scan-and-push:
    name: Secure Docker Build, Trivy Container Scan & AWS ECR Push
    runs-on: ubuntu-latest
    needs: iac-and-static-scan    # if sast or iac scan fails we BLOCKKKKK
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3      #docker buildx est une version amelioree de docker, build rapide, parralele des couches, multi architecture (amd, arm, etc) et moderne!

      # 1. BUILD : pas besoin d'AWS, nom local
      # --load met l'image dans Docker local pour que Trivy la trouve
      - name: Build Docker Image
        run: |
          docker build --load -t ${{ env.ECR_REPOSITORY }}:${{ github.sha }} .

      # 2. SCAN de l'image locale : pas besoin d'AWS
      - name: Trivy Container Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.ECR_REPOSITORY }}:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'














      # 3. AWS : DESACTIVE we do not have aws acc for now
      # Pour reactiver :
      #   a) ajouter les 3 secrets AWS dans GitHub (Settings > Secrets and variables > Actions)
      #   b) enlever les # devant les 3 etapes ci-dessous
      # Le "if" fait que seul le code merge sur main touche AWS, jamais une PR
      #
      # - name: configure aws credentials
      #   if: github.event_name == 'push'
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      #     aws-region: ${{ env.AWS_REGION }}
      #
      # - name: Log in to Amazon ECR
      #   if: github.event_name == 'push'
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v2
      #
      # - name: Tag and push to Amazon ECR
      #   if: github.event_name == 'push'
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #   run: |
      #     docker tag ${{ env.ECR_REPOSITORY }}:${{ github.sha }} $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
      #     docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }}